server.port: 9999

spring:
  application:
    name: gateway-ecommerce
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: billing-route
              uri: lb://billing
              predicates:
                - Path=/api/v1/customers/me/credit-cards,/api/v1/customers/me/credit-cards/{creditCardId}
                - Method=GET,POST,PUT,DELETE,OPTIONS

            - id: ordering-route
              uri: lb://ordering
              predicates:
                - Path=/api/v1/customers/**,/api/v1/shipping-cost-previews,/api/v2/customers/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
              filters:
                - name: CircuitBreaker
                  args:
                    name: ordering-route-cb
                    statusCodes:
                      - 502
                      - 504
                      - 500

            - id: product-catalog-route
              uri: lb://product-catalog
              predicates:
                - Path=/api/v1/products/**,/api/v1/categories/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
              filters:
                - LocalResponseCache=1m,30MB
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 50
                      burstCapacity: 200
                      requestedTokens: 1
                    key-resolver: "#{@rateLimitKeyResolver}"

            - id: user-management-route
              uri: lb://authorization-server
              predicates:
                - Path=/api/v1/users/**
                - Method=GET,POST,PUT,DELETE,OPTIONS

management:
  info:
    env.enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 60s
  circuitbreaker:
    instances:
      ordering-route-cb:
        slidingWindowSize: 8
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10s
        maxWaitDurationInHalfOpenState: 30s
        registerHealthIndicator: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

info:
  app.name: AlgaShop Gateway E-commerce