spring:
  application:
    name: gateway-ecommerce
  data:
    redis:
      host: algashop-redis
      port: 6379
      password: algashop
      database: 4
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.algashop.local:8081
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      endpoint: http://algashop-localstack:4566
    gateway:
      server:
        webflux:
          route-refresh-listener:
            enabled: false
          #          filter:
          #            local-response-cache:
          #              enabled: true
          #              time-to-live: 5m
          #              size: 30MB
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, INTERNAL_SERVER_ERROR
                methods: GET,PUT
                exceptions: java.io.IOException, java.util.concurrent.TimeoutException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 20ms
          httpclient:
            connect-timeout: 1000
            response-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://algashop-service-registry:8761/eureka
    register-with-eureka: false
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, circuitbreakers
  endpoint:
    gateway:
      access: read_only